update action hooks

diff --git a/.openshift/action_hooks/deploy b/.openshift/action_hooks/deploy
--- a/.openshift/action_hooks/deploy
+++ b/.openshift/action_hooks/deploy
@@ -1,14 +1,15 @@
 #!/bin/bash -x
-# This is a simple post deploy hook executed after your application 
-# is deployed and started.  This script gets executed directly, so 
-# it could be python, php, ruby, etc.
+# This deploy hook gets executed after dependencies are resolved and the
+# build hook has been run but before the application has been started back
+# up again.  This script gets executed directly, so it could be python, php,
+# ruby, etc.
 
-echo "Entering post-deploy" | tee -a ${OPENSHIFT_PHP_LOG_DIR}deploy.log
+echo "Entering deploy" | tee -a ${OPENSHIFT_PHP_LOG_DIR}deploy.log
 
 # Ensure db exists
 if [ -z ${OPENSHIFT_POSTGRESQL_DB_HOST} ]; then
 	echo "Database environment not set!" | tee -a ${OPENSHIFT_PHP_LOG_DIR}deploy.log
-	exit 0
+	exit 1
 fi
 
 if [ -f ${OPENSHIFT_DATA_DIR}.schema_deployed ]; then 
@@ -20,16 +21,18 @@ else
     psql -w -f ${OPENSHIFT_REPO_DIR}php/schema/ttrss_schema_pgsql.sql ${OPENSHIFT_APP_NAME} && \
     date >> ${OPENSHIFT_DATA_DIR}.schema_deployed && \
     echo "Schema deployed successfully." | tee -a ${OPENSHIFT_PHP_LOG_DIR}deploy.log
+    OUT=$?
 fi
 
 echo "Updating sphinx." | tee -a ${OPENSHIFT_PHP_LOG_DIR}deploy.log
 # Set up sphinx full-text search
 if [ ! -d ${OPENSHIFT_DATA_DIR}run ]; then
-  echo "***ERROR***: Should have completed during deploy hook."
+  echo "***ERROR***: Should have completed during build hook."
   echo "Configuring Sphinx: Directories" | tee -a ${OPENSHIFT_PHP_LOG_DIR}deploy.log
   mkdir -p ${OPENSHIFT_DATA_DIR}run
   mkdir -p ${OPENSHIFT_DATA_DIR}sphinx/var/data
   mkdir -p ${OPENSHIFT_DATA_DIR}sphinx/etc
+  
   # Configure sphinx for current instance
   echo "Configuring Sphinx: Configuration" | tee -a ${OPENSHIFT_PHP_LOG_DIR}deploy.log
   ${OPENSHIFT_REPO_DIR}misc/sed-sphinx.sh > ${OPENSHIFT_DATA_DIR}sphinx/etc/sphinx.conf
@@ -42,6 +45,7 @@ echo "Starting sphinx." | tee -a ${OPENSHIFT_PHP_LOG_DIR}deploy.log
 ${OPENSHIFT_REPO_DIR}misc/sphinx.sh restart 
 
 echo "Starting Indexer" | tee -a ${OPENSHIFT_PHP_LOG_DIR}deploy.log
-${OPENSHIFT_REPO_DIR}sphinx/bin/indexer --rotate --config ${OPENSHIFT_DATA_DIR}sphinx/etc/sphinx.conf ${OPENSHIFT_APP_NAME} 
-echo "Leaving post-deploy" | tee -a ${OPENSHIFT_PHP_LOG_DIR}deploy.log
-exit 0
+${OPENSHIFT_REPO_DIR}sphinx/bin/indexer --rotate --config ${OPENSHIFT_DATA_DIR}sphinx/etc/sphinx.conf ${OPENSHIFT_APP_NAME}
+ 
+echo "Leaving deploy" | tee -a ${OPENSHIFT_PHP_LOG_DIR}deploy.log
+exit $OUT
